# -*- coding: utf-8 -*-
"""ODE Basic Euler Method.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GFUv1SD_Qhjvd4m2-l-Z86AsX7VzsjEd

## Basic Euler Method — Malaria Case Growth

We use:

$$ \frac{dC}{dt}=rC $$

and Euler's equation:
$$ Cn+1​=Cn​+Δt(rCn​) $$
"""

import numpy as np
import matplotlib.pyplot as plt

# -----------------------------
# Model parameters
# -----------------------------
C0 = 100       # Initial malaria cases
r = 0.20       # Growth rate per day
dt = 1         # Time step = 1 day
days = 30      # Simulation period

# -----------------------------
# Create time array
# -----------------------------
time = np.arange(0, days + dt, dt)

# Create array to store cases
C = np.zeros(len(time))

# Initial condition
C[0] = C0

# -----------------------------
# Euler Method
# -----------------------------
for n in range(len(time) - 1):

    # Calculate rate of change
    dCdt = r * C[n]

    # Euler equation
    C[n + 1] = C[n] + dt * dCdt

# -----------------------------
# Display results
# -----------------------------
for n in range(len(time)):
    print(f"Day {time[n]:.0f}: {C[n]:.2f} cases")

# -----------------------------
# Plot results
# -----------------------------
plt.figure(figsize=(8, 5))

plt.plot(time, C, marker='o')

plt.xlabel("Time (days)")
plt.ylabel("Malaria Cases")
plt.title("Malaria Case Growth Using Euler Method")

plt.grid(True)
plt.show()

"""## Change the growth rate

r = 0.05

r = 0.15

r = 0.20

What does the parameter \(r\) represent biologically?

"""